gcp_setpassword_url = "https://us-west2-supplychainmanagementsystem.cloudfunctions.net/setPassword"
gcp_getaccesslevel_url = "https://us-west2-supplychainmanagementsystem.cloudfunctions.net/getAccessLevel"
encryptkey = "#1$3!#437%&("
hashkey = "#KJHswe%@789&FGHJSkl"

apptitle = "Chain"

azure_hrmanagement_db = "hrmanagement"
azure_hrmanagement_cr = "staff"
azure_hrmanagement_uri = "https://hrmanagement.documents.azure.com:443/"
azure_hrmanagement_readkey = "cF9xu5m3v6v2CcIRSV0loFZaNbnimJe7zgBw4P2822dO2QkXSJxCMw00tijj6PHGP9MwVHb7kj7oo2kY9uuhDA=="
azure_hrmanagement_readwritekey = "hB7hnHmieTR6dPNkL7Bk3U6mQCNDZYbONZtUj7NNiy9yw8zDOToMdMqYuVbxrSTXmqSIvnFulmADYiyuFUfjoQ=="

azure_supplychain_db = "supplychainmanagement"
azure_inventory_db = "inventorymanagement"
azure_inventory_cr = "inventory"
azure_product_category_db = "productmanagement"
azure_product_cr = "product"
azure_productcategory_cr = "productcategory"
azure_supplier_order_db = "suppliermanagement"
azure_supplier_cr = "supplier"
azure_order_cr = "order"
azure_vendor_logistic_order_db = "vendormanagement"
azure_logistic_cr = "logistics"
azure_vendor_cr = "vendor"

azure_supplychain_uri = "https://supplychainmanagement.documents.azure.com:443/"
azure_supplychain_readkey = "UiP2mZyaGEy8uGcwzv9nLeguz97TMerd2zxkeYyzrtu5v2To65axuaqj0Z8MvGC92lcfIUYY0QSWF8Bs7yNthg=="
azure_supplychain_readwritekey = "zg0IM7XXiKMz2D0UfNiQQJD9USRqHeJQbDuJMsAclbnDIHY1GIwvm9BfovWe5kESCEWcDxOGvuUvShPl9zG4Lw=="

demo_azure_supplychain_db = "demosupplychainmanagement"
demo_azure_inventory_db = "demoinventorymanagement"
demo_azure_inventory_cr = "demoinventory"
demo_azure_product_category_db = "demoproductmanagement"
demo_azure_product_cr = "demoproduct"
demo_azure_productcategory_cr = "demoproductcategory"
demo_azure_supplier_order_db = "demosuppliermanagement"
demo_azure_supplier_cr = "demosupplier"
demo_azure_order_cr = "demoorder"
demo_azure_vendor_logistic_order_db = "demovendormanagement"
demo_azure_logistic_cr = "demologistics"
demo_azure_vendor_cr = "demovendor"

demo_azure_supplychain_uri = "https://demosupplychainmanagement.documents.azure.com:443/"
demo_azure_supplychain_readkey = "a1wwMQktqxF8L7cqRknnlb7NNuOcbkkxiSCadL6RcrXFVgBMBXk1kv61qQYrUPEg4o7YhPCATHL5XaPJKqD7KQ=="
demo_azure_supplychain_readwritekey = "dVYgBfTxf14vbQImRO2J6ORcFVU7gbCzQsupDC7cAdnltYRSNEmYRNalqhF71w4q36zPqMmzh1HtkXcJqt3Wvw=="
#sendgrid_key = "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"
sendgrid_key2 = "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"
supportemail = "webservice0023@gmail.com"
